seed: 20
data:
  path: '../../data_processed/LogMaps_Mcdm_IllustrisTNG_LH_z=0.00_Nx128_shiftaugmentedtrain.npy'
  conditional: False

architecture:
  model: baseline
  dim_mults:
    - 1
    - 2
    - 4
    - 8
  init_conv: False
  unet_dim: 64

diffusion:
  beta_schedule: linear_beta_schedule
  schedule_args:
    beta_start: 0.0001
    beta_end: 0.02
  timesteps: 2000
  sampler_args:
    sampler_type: 'uniform'

train:
  epochs: 11
  batch_size: 40
  optimizer: Adam
  learning_rate: 2e-4
  loss_type: huber
